### PR TITLE
feat: disable web admin by config if needed

### PR DESCRIPTION
**Pull request by developerium**
Hi
Since there was no way to disable web admin, I added config check to see if someone is disabled it, if not then go as normal

good day

### CODE REVIEW

**Comment by darkdoon** [comment]
Need ! :+1:

**Comment by developerium** [comment]
this repo is dead!

**Comment by rotimi-best** [comment]
@developerium I am thinking of making a clone of this repo and continue its support. I really love this telegram bot API but sad that Naltox isn't available at all to accept pull requests.

If there are lots of people who would like this repo then we can continue its support, I have tried other ones but I just dislike them. I love the structure of this one.

**Comment by developerium** [comment]
@Rotimi-Best I agree, but I'm no longer working on the project related to this repo

**Comment by rotimi-best** [comment]
I see. Alright. I have lots of projects built upon this repo I even made some changes to the source code to meet my needs. 

I will create the repo anyways you are always welcome to make a pull request when you get back to working on any related projects.

**Pull request closed without merging**
