### PR TITLE
runForm now accepts chatId, fixes #36

### LINKED ISSUE #36: $.runForm could be shown only for requested user?
is there any change to show form only for user who request it?

### PR DESCRIPTION
**Pull request by tunix**
runForm is currently intended to work only with scoped instance. I think we should be able to use it with the original bot instance as well.

For instance I have a group chat where users are supposed to enter some private details about themselves. When they're opted in, bot asks these questions by opening a private chat. My changes allow developers to use both `tg.runForm` (with a required chatId) as well as `$.runForm` (with chatId already assigned by the scope).

### CODE REVIEW

**Comment by tunix** [comment]
@Naltox - if you're OK with these changes, I'm gonna update the README.md file as well.

**Comment by tunix** [comment]
@Naltox could you please at least write why you're rejecting this?

**Comment by Naltox** [comment]
@tunix Hey, sorry for that, i just updated module to 3.0 and all pull requests will not be valid for that, code changed very mush

**Comment by tunix** [comment]
Maybe a roadmap would be nice for contributors?

**Comment by Naltox** [comment]
@tunix Nice suggestion, I'll add it some time

**Pull request closed without merging**
